Pandas:
Pandas is python library used for data manipulation and data analysis. 
Pandas provides a convenient way to analyze and clean data.
Pandas is mostly used for 2D arrays. i.e rows and columns. 2D array is in tabular format.
Pandas has two popular data types. They are :-

Series :- 
series have only one column. 
It is a one dimensional array.
It is more faster then data Frame.
we do not use series that much because in any dataset their are more than 1 columns.


Data frame :- 
data frame can have one or multiple columns. 
It is multi dimensional array.
It is also called as the collection of series.
Data frame is slower than series.

In [74]:
# creating pandas series:
import pandas as pd
list1=[1,2,3,"string"]
list2=[5,6,7,"abcd"]
list3=list1+list2
print(list3)
series=pd.Series(list3) # list3 is represented in a column
print(series)

[1, 2, 3, 'string', 5, 6, 7, 'abcd']
0         1
1         2
2         3
3    string
4         5
5         6
6         7
7      abcd
dtype: object

In [75]:
# if we have to give different index then default index. i.e 0,1,2,3,4,5.......
series1=pd.Series(list3, index=['a','b','c','d','e','f','g','h'])
print(series1)

a         1
b         2
c         3
d    string
e         5
f         6
g         7
h      abcd
dtype: object

Remember the length of list and length of index must be equal otherwise error will occur.

In [76]:
# create a tuple
data= (10,20,30,40,50,60,70)
# create a series from the tuple
my_series = pd.Series(data)
print(my_series)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [77]:
# create a dictionary
grades = {"semester1":['john','ram','hari'],"semester2":3.35,"semester3":2.8}
#grades = [3.14, 2.98, 3.04]
# create a series from the dictionary
my_series = pd.Series (grades)
print(my_series)

semester1    [john, ram, hari]
semester2                 3.35
semester3                  2.8
dtype: object

In dictionary, series treat keyword as index and entire value of that keyword as its single column data.

In [78]:
# in series their an attribute called .index which gives all index of that series.
print(my_series.index)  # gives index
print()
print(my_series.values) # gives values

Index(['semester1', 'semester2', 'semester3'], dtype='object')

[list(['john', 'ram', 'hari']) 3.35 2.8]

In [79]:
s=pd.Series([1,2,3,4,5,6,7])
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [80]:
# creating dataframe

data = {"Name": ['John', 'Alice', 'Bob'], 'Age': [25, 28, 32], 'City': ['New York', 'London', 'Paris']}

df = pd.DataFrame(data)
print(df)

    Name  Age      City
0   John   25  New York
1  Alice   28    London
2    Bob   32     Paris

In dataframe key becomes column head and values of that key becomes its column data as above

data = {'Name': ['John', 'Alice', 'Bob','Rajan'], 
        'Age': [25, 28, 32], 
        'City': ['New York', 'London', 'Paris']}

the above data is inhomogenious data because the length of name keyword is not same with other keywords.

for example

'Name'=['John', 'Alice', 'Bob','Rajan'] # Name have 4 data

'Age': [25, 28, 32] # it has 3 data 

'City': ['New York', 'London', 'Paris'] # it has 3 data

so that all column must have equals number of data

In [81]:
import numpy as np

data = {'Name': ['John', 'Alice', 'Bob','Rajan'], 
        'Age': [25, 28, 32,np.nan], 
        'City': ['New York', 'London', 'Paris',np.nan]}
tabular_data=pd.DataFrame(data)
print(tabular_data)

    Name   Age      City
0   John  25.0  New York
1  Alice  28.0    London
2    Bob  32.0     Paris
3  Rajan   NaN       NaN

we can use np.nan to fill with Nan(null value). it is under numpy so we have to import numpy

In [82]:
data = {'Name': ['John', 'Alice', 'Bob'], 
        'Age': [25, 28, 32], 
        'City': ['New York', 'London', 'Paris']}

df=pd.DataFrame(data,index=pd.RangeIndex(10,13,name='s.n'))
print(df)

      Name  Age      City
s.n
10    John   25  New York
11   Alice   28    London
12     Bob   32     Paris

df=pd.DataFrame(data,index=pd.RangeIndex(10,13,name='s.n'))

above code is used if we need to set the index starting, ending and index name

Note: length of index must be of equal range

In [83]:
# creating data with list of list 
data=[['John', 'Kate', 'Leo'],
    ['IT', 'HR', 'Sales'],
    [50000, 55000, 60000]]

frame_data=pd.DataFrame(data)
print(frame_data)

       0      1      2
0   John   Kate    Leo
1     IT     HR  Sales
2  50000  55000  60000

it have default index and also column name as default index

In [84]:
data=[['John', 25, 'New York'],
    ['Kate', 30, 'London'],
    ['Bob', 28, 'Paris']]

frame_data=pd.DataFrame(data)
frame_data=pd.DataFrame(data,columns=['Name','Age','City'])
print(frame_data)

   Name  Age      City
0  John   25  New York
1  Kate   30    London
2   Bob   28     Paris

frame_data=pd.DataFrame(data,columns=['Name','Age','City'])

in this way we can give manual column name

Data Exploration

df.head() # view top 5 row 

df.head(20) # view top 20 row 

df.tail() # view bottom 5 row 

df.tail(10) # view bottom 10 row

df.sample() # view ramdom single row

df.sample(10) # view random 10 row

Summary statistics:

df.describe() # it gives statistics Summary of the numerical columns i.e int or float

df.describe(include='object') # statistics Summary of numerical column including strings

df.columns -> gives all columns name

df.dtype -> gives the name of the column and type of that column

df.isnull().sum() -> it is used to check the missing values in the column. tells which column have how many missing value

df['column_name'] -> to select a column

df[['column_name','column_name']] -> select multiple column also known as fancy indexing

In [85]:
# to load the excel file 
df = pd.read_excel("employees_dataset.xlsx")
df

,ID,Name,Department,Join_Date,Salary,Performance_Rating,Remote
0,101,Ananya Sharma,IT,2021-03-15,85000,4.2,True
1,102,Rohan Das,HR,2019-07-22,62000,3.8,False
2,103,Vikram Singh,Sales,2022-01-10,75000,4.5,True
3,104,Priya Patel,Marketing,2020-11-05,68000,3.9,True
4,105,Amit Mishra,IT,2018-05-19,95000,4.7,False
5,106,Sneha Reddy,Finance,2023-04-01,82000,4.1,False
6,107,Rahul Verma,Sales,2021-09-12,71000,3.5,True
7,108,Pooja Joshi,HR,2020-02-28,64000,4.0,False
8,109,Kunal Shah,IT,2022-07-15,88000,2.8,True
9,110,Neha Gupta,Marketing,2019-10-03,70000,4.3,False
10,111,Deepak Kumar,Finance,2021-06-20,80000,NaN,True
11,112,Ishita Dutta,IT,2020-08-14,91000,4.6,False
12,113,Siddharth Rao,Sales,2023-01-25,73000,3.7,True
13,114,Kavita Nair,HR,2017-12-01,67000,4.4,False
14,115,Manoj Tiwari,Marketing,2022-11-30,69000,3.2,True
15,116,Divya Saxena,Finance,2018-09-09,86000,4.8,False
16,117,Rajesh Choudhary,IT,2021-12-05,87000,3.9,True
17,118,Aarti Kapoor,Sales,2020-04-18,74000,4.1,False
18,119,Varun Dhawan,Marketing,2023-03-10,66000,NaN,True
19,120,Meera Bai,HR,2019-05-24,63000,3.6,False

In [86]:
# to see all the columns
df.columns

Index(['ID', 'Name', 'Department', 'Join_Date', 'Salary', 'Performance_Rating',
       'Remote'],
      dtype='object')

In [87]:
# to get full information of all columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  20 non-null     int64
 1   Name                20 non-null     object
 2   Department          20 non-null     object
 3   Join_Date           20 non-null     object
 4   Salary              20 non-null     int64
 5   Performance_Rating  18 non-null     float64
 6   Remote              20 non-null     bool
dtypes: bool(1), float64(1), int64(2), object(3)
memory usage: 1.1+ KB

In [88]:
# to see number of row and number of columns
df.shape

(20, 7)

In [89]:
# to see the which column have which data type
df.dtypes

ID                      int64
Name                   object
Department             object
Join_Date              object
Salary                  int64
Performance_Rating    float64
Remote                   bool
dtype: object

In [90]:
# to see mathematical summary of numerical columns 
df.describe()

              ID       Salary  Performance_Rating
count   20.00000     20.00000           18.000000
mean   110.50000  75800.00000            4.005556
std      5.91608  10159.77621            0.525214
min    101.00000  62000.00000            2.800000
25%    105.75000  67750.00000            3.725000
50%    110.50000  73500.00000            4.050000
75%    115.25000  85250.00000            4.375000
max    120.00000  95000.00000            4.800000

In [91]:
# to see catagorical summary of the column whose data_type is object
df.describe(include="object")

                 Name Department   Join_Date
count              20         20          20
unique             20          5          20
top     Ananya Sharma         IT  2021-03-15
freq                1          5           1

In [92]:
# to see the summary of all the columns 
df.describe(include="all")

,ID,Name,Department,Join_Date,Salary,Performance_Rating,Remote
count,20.00000,20,20,20,20.00000,18.000000,20
unique,NaN,20,5,20,NaN,NaN,2
top,NaN,Ananya Sharma,IT,2021-03-15,NaN,NaN,True
freq,NaN,1,5,1,NaN,NaN,10
mean,110.50000,NaN,NaN,NaN,75800.00000,4.005556,NaN
std,5.91608,NaN,NaN,NaN,10159.77621,0.525214,NaN
min,101.00000,NaN,NaN,NaN,62000.00000,2.800000,NaN
25%,105.75000,NaN,NaN,NaN,67750.00000,3.725000,NaN
50%,110.50000,NaN,NaN,NaN,73500.00000,4.050000,NaN
75%,115.25000,NaN,NaN,NaN,85250.00000,4.375000,NaN
max,120.00000,NaN,NaN,NaN,95000.00000,4.800000,NaN

In [93]:
# to remove a colum 
df = df.drop(columns=['Remote'])
df

     ID              Name Department   Join_Date  Salary  Performance_Rating
0   101     Ananya Sharma         IT  2021-03-15   85000                 4.2
1   102         Rohan Das         HR  2019-07-22   62000                 3.8
2   103      Vikram Singh      Sales  2022-01-10   75000                 4.5
3   104       Priya Patel  Marketing  2020-11-05   68000                 3.9
4   105       Amit Mishra         IT  2018-05-19   95000                 4.7
5   106       Sneha Reddy    Finance  2023-04-01   82000                 4.1
6   107       Rahul Verma      Sales  2021-09-12   71000                 3.5
7   108       Pooja Joshi         HR  2020-02-28   64000                 4.0
8   109        Kunal Shah         IT  2022-07-15   88000                 2.8
9   110        Neha Gupta  Marketing  2019-10-03   70000                 4.3
10  111      Deepak Kumar    Finance  2021-06-20   80000                 NaN
11  112      Ishita Dutta         IT  2020-08-14   91000                 4.6
12  113     Siddharth Rao      Sales  2023-01-25   73000                 3.7
13  114       Kavita Nair         HR  2017-12-01   67000                 4.4
14  115      Manoj Tiwari  Marketing  2022-11-30   69000                 3.2
15  116      Divya Saxena    Finance  2018-09-09   86000                 4.8
16  117  Rajesh Choudhary         IT  2021-12-05   87000                 3.9
17  118      Aarti Kapoor      Sales  2020-04-18   74000                 4.1
18  119      Varun Dhawan  Marketing  2023-03-10   66000                 NaN
19  120         Meera Bai         HR  2019-05-24   63000                 3.6

In [94]:
# to remove row 
df= df.drop([7]) # 7th row is delected
df

     ID              Name Department   Join_Date  Salary  Performance_Rating
0   101     Ananya Sharma         IT  2021-03-15   85000                 4.2
1   102         Rohan Das         HR  2019-07-22   62000                 3.8
2   103      Vikram Singh      Sales  2022-01-10   75000                 4.5
3   104       Priya Patel  Marketing  2020-11-05   68000                 3.9
4   105       Amit Mishra         IT  2018-05-19   95000                 4.7
5   106       Sneha Reddy    Finance  2023-04-01   82000                 4.1
6   107       Rahul Verma      Sales  2021-09-12   71000                 3.5
8   109        Kunal Shah         IT  2022-07-15   88000                 2.8
9   110        Neha Gupta  Marketing  2019-10-03   70000                 4.3
10  111      Deepak Kumar    Finance  2021-06-20   80000                 NaN
11  112      Ishita Dutta         IT  2020-08-14   91000                 4.6
12  113     Siddharth Rao      Sales  2023-01-25   73000                 3.7
13  114       Kavita Nair         HR  2017-12-01   67000                 4.4
14  115      Manoj Tiwari  Marketing  2022-11-30   69000                 3.2
15  116      Divya Saxena    Finance  2018-09-09   86000                 4.8
16  117  Rajesh Choudhary         IT  2021-12-05   87000                 3.9
17  118      Aarti Kapoor      Sales  2020-04-18   74000                 4.1
18  119      Varun Dhawan  Marketing  2023-03-10   66000                 NaN
19  120         Meera Bai         HR  2019-05-24   63000                 3.6

In [95]:
# to add new column
names_list = [
    "Liam", "Noah", "Oliver", "Elijah", "Lucas", 
    "Emma", "Olivia", "Ava", "Sophia", "Isabella", 
    "Alexander", "Benjamin", "William", "James", "Henry", 
    "Charlotte", "Amelia", "Mia", "Evelyn",
]
df['assistant']=names_list
df

,ID,Name,Department,Join_Date,Salary,Performance_Rating,assistant
0,101,Ananya Sharma,IT,2021-03-15,85000,4.2,Liam
1,102,Rohan Das,HR,2019-07-22,62000,3.8,Noah
2,103,Vikram Singh,Sales,2022-01-10,75000,4.5,Oliver
3,104,Priya Patel,Marketing,2020-11-05,68000,3.9,Elijah
4,105,Amit Mishra,IT,2018-05-19,95000,4.7,Lucas
5,106,Sneha Reddy,Finance,2023-04-01,82000,4.1,Emma
6,107,Rahul Verma,Sales,2021-09-12,71000,3.5,Olivia
8,109,Kunal Shah,IT,2022-07-15,88000,2.8,Ava
9,110,Neha Gupta,Marketing,2019-10-03,70000,4.3,Sophia
10,111,Deepak Kumar,Finance,2021-06-20,80000,NaN,Isabella
11,112,Ishita Dutta,IT,2020-08-14,91000,4.6,Alexander
12,113,Siddharth Rao,Sales,2023-01-25,73000,3.7,Benjamin
13,114,Kavita Nair,HR,2017-12-01,67000,4.4,William
14,115,Manoj Tiwari,Marketing,2022-11-30,69000,3.2,James
15,116,Divya Saxena,Finance,2018-09-09,86000,4.8,Henry
16,117,Rajesh Choudhary,IT,2021-12-05,87000,3.9,Charlotte
17,118,Aarti Kapoor,Sales,2020-04-18,74000,4.1,Amelia
18,119,Varun Dhawan,Marketing,2023-03-10,66000,NaN,Mia
19,120,Meera Bai,HR,2019-05-24,63000,3.6,Evelyn

In [96]:
# set_index() is used to make any column as index
df.set_index('Name',inplace=True) # set name column as index and inplace=True make the changes in the dataframe df
# set_index() does not work if there is no inplace=True 
df

,ID,Department,Join_Date,Salary,Performance_Rating,assistant
Name,,,,,,
Ananya Sharma,101,IT,2021-03-15,85000,4.2,Liam
Rohan Das,102,HR,2019-07-22,62000,3.8,Noah
Vikram Singh,103,Sales,2022-01-10,75000,4.5,Oliver
Priya Patel,104,Marketing,2020-11-05,68000,3.9,Elijah
Amit Mishra,105,IT,2018-05-19,95000,4.7,Lucas
Sneha Reddy,106,Finance,2023-04-01,82000,4.1,Emma
Rahul Verma,107,Sales,2021-09-12,71000,3.5,Olivia
Kunal Shah,109,IT,2022-07-15,88000,2.8,Ava
Neha Gupta,110,Marketing,2019-10-03,70000,4.3,Sophia
Deepak Kumar,111,Finance,2021-06-20,80000,NaN,Isabella
Ishita Dutta,112,IT,2020-08-14,91000,4.6,Alexander
Siddharth Rao,113,Sales,2023-01-25,73000,3.7,Benjamin
Kavita Nair,114,HR,2017-12-01,67000,4.4,William
Manoj Tiwari,115,Marketing,2022-11-30,69000,3.2,James
Divya Saxena,116,Finance,2018-09-09,86000,4.8,Henry
Rajesh Choudhary,117,IT,2021-12-05,87000,3.9,Charlotte
Aarti Kapoor,118,Sales,2020-04-18,74000,4.1,Amelia
Varun Dhawan,119,Marketing,2023-03-10,66000,NaN,Mia
Meera Bai,120,HR,2019-05-24,63000,3.6,Evelyn